language: objective-c
python:
  - "3.5"
#install deps
before_install:
	- brew update
	- brew install python3 
	- which python3 
	- brew install python
	- which pip3 
	- python3 --version 
	- pip3 install -r dependencies.txt
#run tests
script: py.test-3.5

install: python3 setup.py py2app 
